import type { Metadata } from "next";
import { NextUIProvider } from "@nextui-org/react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextUIProvider >
      <Header />
      {children}
      <Footer />
    </NextUIProvider>
  );
}
